pipeline {
    agent {
        // This targets the Docker container you just built and connected
        label "agent-1" 
    }
    
    stages {
        stage("Code Checkout") {
            steps {
                echo "Cloning the repository..."
                // Cloning your specific repository
                git url: "https://github.com/sanepunk/Jenkins-Tut.git", branch: "main"
            }
        }

        stage("Setup & Test") {
            steps {
                echo "Setting up Virtual Environment and Testing..."
                script {
                    // Since your agent is Linux-based (jenkins/inbound-agent), we use 'sh'
                    sh '''
                        echo "--- Checking Python Version ---"
                        python3 --version

                        echo "--- Creating Virtual Environment ---"
                        # 1. Create a clean environment named 'venv'
                        python3 -m venv venv

                        # 2. Activate it (Standard Linux way)
                        . venv/bin/activate

                        echo "--- Installing Dependencies ---"
                        # 3. Upgrade pip and install your requirements
                        pip install --upgrade pip
                        pip install -r requirements.txt

                        echo "--- Running Tests ---"
                        # 4. Run Pytest
                        # -v: Verbose (show test names)
                        # --junitxml: Generate report for Jenkins to read
                        python -m pytest test_resource_heavy.py -v --junitxml=test-results.xml
                    '''
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline finished. Collecting results..."
            // This reads the XML file generated by pytest and makes a graph in Jenkins
            junit allowEmptyResults: true, testResults: 'test-results.xml'
        }
        success {
            echo "✅ SUCCESS: All ML tests passed!"
        }
        failure {
            echo "❌ FAILURE: Some tests failed. Check the logs."
        }
    }
}